### ISSUE TITLE
test_distance_query fails

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#132]
```
ERROR: test_distance_query (storybase_story.tests.StoryExploreResourceTest)
----------------------------------------------------------------------
Traceback (most recent call last):

File "/home/vagrant/builds/PitonFoundation/atlas/apps/storybase_story/tests.py", line 1163, in test_distance_query
resp = self.resource.explore_get_list(req)
File "/home/vagrant/builds/PitonFoundation/atlas/apps/storybase_story/api.py", line 305, in explore_get_list request, **kwargs)
File "/home/vagrant/builds/PitonFoundation/atlas/apps/storybase_story/api.py", line 289, in explore_get_data_to_be_serialized
for facet_field, items in results.facet_counts()['fields'].iteritems():
KeyError: 'fields'
```

**Comment by ghing** [comment]
This only fails when using Haystack's haystack.backends.simple_backend.SimpleEngine backend.

**Comment by ghing** [comment]
This only fails when using Haystack's haystack.backends.simple_backend.SimpleEngine backend.

**Comment by ghing** [comment]
This was due to SimpleEngine not supporting faceting. I updated the Travis CI build to set up Solr and for Haystack to use the Solr backend and this test now passes.
