### ISSUE TITLE
Upgrade to Django 1.4

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#35]
The upgrade is blocking on these issues in dependencies:

https://github.com/ojii/django-sekizai/pull/14
https://github.com/divio/django-cms/issues/search?q=1.4

**Comment by ghing** [comment]
Djanco CMS 2.3 is now out which includes support for Django 1.4

**Comment by ghing** [comment]
Right now I'm getting this error message when running the unit tests.  I still need to track down which tests are causing this, but it does not cause any tests to fail.

```
Problem installing fixture 'story_templates.json.bz2': Traceback (most recent call last):
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 226, in handle
    connection.check_constraints(table_names=table_names)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 323, in check_constraints
    referenced_table_name, referenced_column_name))
IntegrityError: The row in table 'storybase_story_story' with primary key '1' has an invalid foreign key: storybase_story_story.author_id contains a value '1' that does not have a corresponding value in auth_user.id.
```

It does not cause any unit tests to break.  It's a result of the fixture expecting an admin user to exist to set ownership of the template stories and probably relatively easy to create the user prior to running the tests.

The following unit tests are failing, probably due to PIL being build without the right image file support.

```
======================================================================
ERROR: test_get_list (storybase_asset.tests.AssetResourceFeaturedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ghing/workspace/atlas/apps/storybase_asset/tests.py", line 1542, in test_get_list
    resp = self.api_client.get(uri, format='json')
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/tastypie/test.py", line 60, in get
    return self.client.get(uri, **kwargs)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/django/test/client.py", line 439, in get
    response = super(Client, self).get(path, data=data, **extra)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/django/test/client.py", line 244, in get
    return self.request(**r)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/tastypie/resources.py", line 202, in wrapper
    response = callback(request, *args, **kwargs)
  File "/home/ghing/workspace/atlas/apps/storybase_asset/api.py", line 112, in dispatch_featured_list
    return self.dispatch('featured_list', request, **kwargs)
  File "/home/ghing/workspace/atlas/apps/storybase/api/resources.py", line 344, in dispatch
    response = method(request, **kwargs)
  File "/home/ghing/workspace/atlas/apps/storybase_asset/api.py", line 122, in get_featured_list
    return self.get_list(request, **kwargs)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/tastypie/resources.py", line 1135, in get_list
    to_be_serialized[self._meta.collection_name] = [self.full_dehydrate(bundle) for bundle in bundles]
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/tastypie/resources.py", line 745, in full_dehydrate
    bundle.data[field_name] = method(bundle)
  File "/home/ghing/workspace/atlas/apps/storybase_asset/api.py", line 237, in dehydrate_thumbnail_url
    return bundle.obj.get_thumbnail_url(width=222, height=222)
  File "/home/ghing/workspace/atlas/apps/storybase_asset/models.py", line 553, in get_thumbnail_url
    thumbnail = thumbnailer.get_thumbnail(thumbnail_options)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/easy_thumbnails/files.py", line 396, in get_thumbnail
    thumbnail = self.generate_thumbnail(thumbnail_options)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/easy_thumbnails/files.py", line 292, in generate_thumbnail
    "The source file does not appear to be an image")
InvalidImageFormatError: The source file does not appear to be an image

======================================================================
ERROR: test_put_list (storybase_asset.tests.AssetResourceFeaturedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ghing/workspace/atlas/apps/storybase_asset/tests.py", line 1571, in test_put_list
    resp = self.api_client.put(uri, format='json', data=put_data)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/tastypie/test.py", line 132, in put
    return self.client.put(uri, **kwargs)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/django/test/client.py", line 477, in put
    response = super(Client, self).put(path, data=data, content_type=content_type, **extra)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/django/test/client.py", line 305, in put
    return self.request(**r)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/tastypie/resources.py", line 202, in wrapper
    response = callback(request, *args, **kwargs)
  File "/home/ghing/workspace/atlas/apps/storybase_asset/api.py", line 112, in dispatch_featured_list
    return self.dispatch('featured_list', request, **kwargs)
  File "/home/ghing/workspace/atlas/apps/storybase/api/resources.py", line 344, in dispatch
    response = method(request, **kwargs)
  File "/home/ghing/workspace/atlas/apps/storybase_asset/api.py", line 145, in put_featured_list
    to_be_serialized['objects'] = [self.full_dehydrate(bundle) for bundle in bundles]
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/tastypie/resources.py", line 745, in full_dehydrate
    bundle.data[field_name] = method(bundle)
  File "/home/ghing/workspace/atlas/apps/storybase_asset/api.py", line 237, in dehydrate_thumbnail_url
    return bundle.obj.get_thumbnail_url(width=222, height=222)
  File "/home/ghing/workspace/atlas/apps/storybase_asset/models.py", line 553, in get_thumbnail_url
    thumbnail = thumbnailer.get_thumbnail(thumbnail_options)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/easy_thumbnails/files.py", line 396, in get_thumbnail
    thumbnail = self.generate_thumbnail(thumbnail_options)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/easy_thumbnails/files.py", line 292, in generate_thumbnail
    "The source file does not appear to be an image")
InvalidImageFormatError: The source file does not appear to be an image

======================================================================
ERROR: test_get_detail_image (storybase_asset.tests.AssetResourceTest)
Test getting the details for a locally-stored image asset
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ghing/workspace/atlas/apps/storybase_asset/tests.py", line 1037, in test_get_detail_image
    resp = self.api_client.get(uri)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/tastypie/test.py", line 60, in get
    return self.client.get(uri, **kwargs)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/django/test/client.py", line 439, in get
    response = super(Client, self).get(path, data=data, **extra)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/django/test/client.py", line 244, in get
    return self.request(**r)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/tastypie/resources.py", line 202, in wrapper
    response = callback(request, *args, **kwargs)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/tastypie/resources.py", line 450, in dispatch_detail
    return self.dispatch('detail', request, **kwargs)
  File "/home/ghing/workspace/atlas/apps/storybase/api/resources.py", line 344, in dispatch
    response = method(request, **kwargs)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/tastypie/resources.py", line 1156, in get_detail
    bundle = self.full_dehydrate(bundle)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/tastypie/resources.py", line 745, in full_dehydrate
    bundle.data[field_name] = method(bundle)
  File "/home/ghing/workspace/atlas/apps/storybase_asset/api.py", line 237, in dehydrate_thumbnail_url
    return bundle.obj.get_thumbnail_url(width=222, height=222)
  File "/home/ghing/workspace/atlas/apps/storybase_asset/models.py", line 553, in get_thumbnail_url
    thumbnail = thumbnailer.get_thumbnail(thumbnail_options)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/easy_thumbnails/files.py", line 396, in get_thumbnail
    thumbnail = self.generate_thumbnail(thumbnail_options)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/easy_thumbnails/files.py", line 292, in generate_thumbnail
    "The source file does not appear to be an image")
InvalidImageFormatError: The source file does not appear to be an image

======================================================================
ERROR: test_post_list_image (storybase_asset.tests.AssetResourceTest)
Test creating a asset with the data stored in an uploaded image
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ghing/workspace/atlas/apps/storybase_asset/tests.py", line 1067, in test_post_list_image
    format='json', data=post_data)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/tastypie/test.py", line 96, in post
    return self.client.post(uri, **kwargs)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/django/test/client.py", line 449, in post
    response = super(Client, self).post(path, data=data, content_type=content_type, **extra)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/django/test/client.py", line 262, in post
    return self.request(**r)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/tastypie/resources.py", line 202, in wrapper
    response = callback(request, *args, **kwargs)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/tastypie/resources.py", line 441, in dispatch_list
    return self.dispatch('list', request, **kwargs)
  File "/home/ghing/workspace/atlas/apps/storybase/api/resources.py", line 344, in dispatch
    response = method(request, **kwargs)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/tastypie/resources.py", line 1264, in post_list
    updated_bundle = self.full_dehydrate(updated_bundle)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/tastypie/resources.py", line 745, in full_dehydrate
    bundle.data[field_name] = method(bundle)
  File "/home/ghing/workspace/atlas/apps/storybase_asset/api.py", line 237, in dehydrate_thumbnail_url
    return bundle.obj.get_thumbnail_url(width=222, height=222)
  File "/home/ghing/workspace/atlas/apps/storybase_asset/models.py", line 553, in get_thumbnail_url
    thumbnail = thumbnailer.get_thumbnail(thumbnail_options)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/easy_thumbnails/files.py", line 396, in get_thumbnail
    thumbnail = self.generate_thumbnail(thumbnail_options)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/easy_thumbnails/files.py", line 292, in generate_thumbnail
    "The source file does not appear to be an image")
InvalidImageFormatError: The source file does not appear to be an image

======================================================================
ERROR: test_put_detail_image_relative_url (storybase_asset.tests.AssetResourceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ghing/workspace/atlas/apps/storybase_asset/tests.py", line 1180, in test_put_detail_image_relative_url
    resp = self.api_client.get(base_uri)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/tastypie/test.py", line 60, in get
    return self.client.get(uri, **kwargs)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/django/test/client.py", line 439, in get
    response = super(Client, self).get(path, data=data, **extra)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/django/test/client.py", line 244, in get
    return self.request(**r)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/tastypie/resources.py", line 202, in wrapper
    response = callback(request, *args, **kwargs)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/tastypie/resources.py", line 450, in dispatch_detail
    return self.dispatch('detail', request, **kwargs)
  File "/home/ghing/workspace/atlas/apps/storybase/api/resources.py", line 344, in dispatch
    response = method(request, **kwargs)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/tastypie/resources.py", line 1156, in get_detail
    bundle = self.full_dehydrate(bundle)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/tastypie/resources.py", line 745, in full_dehydrate
    bundle.data[field_name] = method(bundle)
  File "/home/ghing/workspace/atlas/apps/storybase_asset/api.py", line 237, in dehydrate_thumbnail_url
    return bundle.obj.get_thumbnail_url(width=222, height=222)
  File "/home/ghing/workspace/atlas/apps/storybase_asset/models.py", line 553, in get_thumbnail_url
    thumbnail = thumbnailer.get_thumbnail(thumbnail_options)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/easy_thumbnails/files.py", line 396, in get_thumbnail
    thumbnail = self.generate_thumbnail(thumbnail_options)
  File "/home/ghing/venvs/floodlight/local/lib/python2.7/site-packages/easy_thumbnails/files.py", line 292, in generate_thumbnail
    "The source file does not appear to be an image")
InvalidImageFormatError: The source file does not appear to be an image

----------------------------------------------------------------------
```

**Comment by ghing** [comment]
After switching from PIL to Pillow, it appears that all unit tests pass.

**Comment by ghing** [comment]
I was able to get the development server up and running.  

Note that with this upgrade, you have to run:

```
manage.py migrate cms
```

after upgrading the django-cms package.

**Comment by ghing** [comment]
TODO: Use Django 1.4's `verbatim` tag if it's available, otherwise backport it.  [This](https://gist.github.com/1350641) seems like a reasonable pattern for backporting template tags.
