### ISSUE TITLE
IndexError when trying to add a project or organization

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#493]
This is when trying to load (GET not POST) /admin/storybase_user/organization/add/ and /admin/storybase_user/project/add/

I wasn't able to replicate this on the development instance.

Traceback (most recent call last):

```
      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
        response = callback(request, *callback_args, **callback_kwargs)

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/contrib/admin/options.py", line 307, in wrapper
        return self.admin_site.admin_view(view)(*args, **kwargs)

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 93, in _wrapped_view
        response = view_func(request, *args, **kwargs)

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/views/decorators/cache.py", line 79, in _wrapped_view_func
        response = view_func(request, *args, **kwargs)

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 197, in inner
        return view(request, *args, **kwargs)

      File "/home/floodlight/webapps/floodlight_production/floodlight/apps/storybase/admin.py", line 33, in add_view
        extra_context=extra_context)

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 28, in _wrapper
        return bound_func(*args, **kwargs)

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 93, in _wrapped_view
        response = view_func(request, *args, **kwargs)

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 24, in bound_func
        return func(self, *args2, **kwargs2)

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/db/transaction.py", line 217, in inner
        res = func(*args, **kwargs)

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/contrib/admin/options.py", line 938, in add_view
        return self.render_change_form(request, context, form_url=form_url, add=True)

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/contrib/admin/options.py", line 708, in render_change_form
        ], context, context_instance=context_instance)

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 20, in render_to_response
        return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/loader.py", line 188, in render_to_string
        return t.render(context_instance)

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/base.py", line 123, in render
        return self._render(context)

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/base.py", line 117, in _render
        return self.nodelist.render(context)

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/base.py", line 744, in render
        bits.append(self.render_node(node, context))

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/base.py", line 757, in render_node
        return node.render(context)

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/loader_tags.py", line 127, in render
        return compiled_parent._render(context)

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/base.py", line 117, in _render
        return self.nodelist.render(context)

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/base.py", line 744, in render
        bits.append(self.render_node(node, context))

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/base.py", line 757, in render_node
        return node.render(context)

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/loader_tags.py", line 127, in render
        return compiled_parent._render(context)

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/base.py", line 117, in _render
        return self.nodelist.render(context)

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/base.py", line 744, in render
        bits.append(self.render_node(node, context))

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/base.py", line 757, in render_node
        return node.render(context)

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/loader_tags.py", line 64, in render
        result = block.nodelist.render(context)

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/base.py", line 744, in render
        bits.append(self.render_node(node, context))

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/base.py", line 757, in render_node
        return node.render(context)

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/defaulttags.py", line 227, in render
        nodelist.append(node.render(context))

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/loader_tags.py", line 159, in render
        return self.render_template(self.template, context)

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/loader_tags.py", line 141, in render_template
        output = template.render(context)

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/base.py", line 123, in render
        return self._render(context)

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/base.py", line 117, in _render
        return self.nodelist.render(context)

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/base.py", line 744, in render
        bits.append(self.render_node(node, context))

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/base.py", line 757, in render_node
        return node.render(context)

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/defaulttags.py", line 227, in render
        nodelist.append(node.render(context))

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/defaulttags.py", line 227, in render
        nodelist.append(node.render(context))

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/defaulttags.py", line 313, in render
        return self.nodelist_false.render(context)

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/base.py", line 744, in render
        bits.append(self.render_node(node, context))

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/base.py", line 757, in render_node
        return node.render(context)

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/defaulttags.py", line 313, in render
        return self.nodelist_false.render(context)

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/base.py", line 744, in render
        bits.append(self.render_node(node, context))

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/base.py", line 757, in render_node
        return node.render(context)

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/base.py", line 797, in render
        return _render_value_in_context(output, context)

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/base.py", line 777, in _render_value_in_context
        value = force_unicode(value)

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/utils/encoding.py", line 71, in force_unicode
        s = unicode(s)

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/forms/forms.py", line 408, in __unicode__
        return self.as_widget()

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/forms/forms.py", line 439, in as_widget
        return widget.render(name, self.value(), attrs=attrs)

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/contrib/admin/widgets.py", line 240, in render
        output = [self.widget.render(name, value, *args, **kwargs)]

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/contrib/admin/widgets.py", line 39, in render
        output = [super(FilteredSelectMultiple, self).render(name, value, attrs, choices)]

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/forms/widgets.py", line 581, in render
        options = self.render_options(choices, value)

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/forms/widgets.py", line 533, in render_options
        for option_value, option_label in chain(self.choices, choices):

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/forms/models.py", line 883, in __iter__
        yield self.choice(obj)

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/forms/models.py", line 889, in choice
        return (self.field.prepare_value(obj), self.field.label_from_instance(obj))

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/forms/models.py", line 940, in label_from_instance
        return smart_unicode(obj)

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/utils/encoding.py", line 39, in smart_unicode
        return force_unicode(s, encoding, strings_only, errors)

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/utils/encoding.py", line 71, in force_unicode
        s = unicode(s)

      File "/home/floodlight/webapps/floodlight_production/floodlight/apps/storybase_asset/models.py", line 140, in __unicode__
        return subclass_obj.__unicode__()

      File "/home/floodlight/webapps/floodlight_production/floodlight/apps/storybase_asset/models.py", line 282, in __unicode__
        if self.title:

      File "/home/floodlight/webapps/floodlight_production/floodlight/apps/storybase/models/translation.py", line 76, in __getattribute__
        translated_object = translated_manager.all()[0]

      File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/db/models/query.py", line 190, in __getitem__
        return list(qs)[0]

    IndexError: list index out of range
```

**Comment by ghing** [comment]
@jwirfs-brock This is the issue you reported to me via email

**Comment by ghing** [comment]
This appears to be a data-related issue.  I wasn't able to replicate this on the development server or on the staging instance of the production server with the same software version as the production instance.  When I synced the staging instance data with the production database, I was able to replicate the issue.

**Comment by ghing** [comment]
@jwirfs-brock I've fixed this at the data level.  I still need to deploy code changes that log a helpful error message in the event that this happens again to be able to fix it faster.  We should talk tomorrow to figure out what caused the issue. It looks like the "broken" asset was one that you created somehow.

**Comment by ghing** [comment]
This is the scenario from @jwirfs-brock that may have caused creating the translationless assets in the builder:

> I had created a text asset
> but then didn't click "save changes"
> and then I tried to do some other things (I think I added some new sections, triggering the auto-save)
> and when I did that, the text asset I had not saved disappeared
> (I often forget to click "save changes" when creating a text asset, because you don't have to do that for the 
> summary, and sometimes you can't see the button, depending on the size of your browser window)
