### ISSUE TITLE
Wiring of messages changes with django-notification 1.0

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#571]
Tests on Travis CI are failing because django-notification-1.0 (which must have recently been pushed to PyPi) has changed the way notifications are wired up.

Traceback:

```
Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    execute_manager(settings)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 438, in execute_manager
    utility.execute()
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 379, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/django/core/management/base.py", line 191, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/django/core/management/base.py", line 220, in execute
    output = self.handle(*args, **options)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/south/management/commands/test.py", line 8, in handle
    super(Command, self).handle(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/django/core/management/commands/test.py", line 37, in handle
    failures = test_runner.run_tests(test_labels)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/django/test/simple.py", line 359, in run_tests
    old_config = self.setup_databases()
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/django/test/simple.py", line 296, in setup_databases
    test_db_name = connection.creation.create_test_db(self.verbosity, autoclobber=not self.interactive)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/django/db/backends/creation.py", line 366, in create_test_db
    load_initial_data=False)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 166, in call_command
    return klass.execute(*args, **defaults)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/django/core/management/base.py", line 220, in execute
    output = self.handle(*args, **options)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/django/core/management/base.py", line 351, in handle
    return self.handle_noargs(**options)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/django/core/management/commands/syncdb.py", line 109, in handle_noargs
    emit_post_sync_signal(created_models, verbosity, interactive, db)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/django/core/management/sql.py", line 190, in emit_post_sync_signal
    interactive=interactive, db=db)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 172, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/travis/builds/PitonFoundation/atlas/apps/storybase_messaging/management.py", line 12, in create_notice_types
    notification.create_notice_type("system_message", _("System Message"),
AttributeError: 'module' object has no attribute 'create_notice_type'
```

**Comment by ghing** [comment]
This has been fixed.
