### ISSUE TITLE
Geocoding tests failing

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#572]
Traceback:

```
======================================================================
ERROR: test_geocode_with_default_geocoder (storybase_geo.tests.GeocoderResourceTest)
Test geocoding with default geocoder
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/builds/PitonFoundation/atlas/apps/storybase_geo/tests.py", line 108, in test_geocode_with_default_geocoder
    self.assertEqual(results[0].lat, 39.7434926)
IndexError: list index out of range

======================================================================
ERROR: test_delete_detail_unauthorized (storybase_geo.tests.LocationResourceTest)
Tests that an unauthorized user cannot delete a location
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/builds/PitonFoundation/atlas/apps/storybase_geo/tests.py", line 337, in test_delete_detail_unauthorized
    obj = Location.objects.create(**self.location_attrs[0])
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/django/db/models/manager.py", line 138, in create
    return self.get_query_set().create(**kwargs)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/django/db/models/query.py", line 360, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/django/db/models/base.py", line 460, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/django/db/models/base.py", line 484, in save_base
    signals.pre_save.send(sender=origin, instance=self, raw=raw, using=using)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 172, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/travis/builds/PitonFoundation/atlas/apps/storybase_geo/models.py", line 119, in geocode
    instance.postcode))
  File "/home/travis/builds/PitonFoundation/atlas/apps/storybase_geo/models.py", line 97, in _geocode
    results = list(geocoder.geocode(address, exactly_one=False))
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/geopy/geocoders/openmapquest.py", line 39, in geocode
    return self.parse_json(page, exactly_one)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/geopy/geocoders/openmapquest.py", line 45, in parse_json
    resources = json.loads(page)
  File "/usr/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

======================================================================
ERROR: test_get_list_with_story (storybase_geo.tests.LocationResourceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/builds/PitonFoundation/atlas/apps/storybase_geo/tests.py", line 225, in test_get_list_with_story
    Location.objects.create(**attrs)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/django/db/models/manager.py", line 138, in create
    return self.get_query_set().create(**kwargs)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/django/db/models/query.py", line 360, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/django/db/models/base.py", line 460, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/django/db/models/base.py", line 484, in save_base
    signals.pre_save.send(sender=origin, instance=self, raw=raw, using=using)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 172, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/travis/builds/PitonFoundation/atlas/apps/storybase_geo/models.py", line 119, in geocode
    instance.postcode))
  File "/home/travis/builds/PitonFoundation/atlas/apps/storybase_geo/models.py", line 97, in _geocode
    results = list(geocoder.geocode(address, exactly_one=False))
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/geopy/geocoders/openmapquest.py", line 39, in geocode
    return self.parse_json(page, exactly_one)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/geopy/geocoders/openmapquest.py", line 45, in parse_json
    resources = json.loads(page)
  File "/usr/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by ghing** [comment]
This doesn't seem to be an issue any more.  Closing.
