### ISSUE TITLE
TypeError when running tests under Travis

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#594]
```
======================================================================
ERROR: test_distance_query (storybase_story.tests.StoryExploreResourceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/PitonFoundation/atlas/apps/storybase_story/tests.py", line 2980, in setUp
    self._rebuild_index()
  File "/home/travis/build/PitonFoundation/atlas/apps/storybase_story/tests.py", line 2985, in _rebuild_index
    call_command('rebuild_index', interactive=False, verbosity=0)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 166, in call_command
    return klass.execute(*args, **defaults)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/django/core/management/base.py", line 220, in execute
    output = self.handle(*args, **options)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/haystack/management/commands/rebuild_index.py", line 15, in handle
    call_command('update_index', **options)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 166, in call_command
    return klass.execute(*args, **defaults)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/django/core/management/base.py", line 220, in execute
    output = self.handle(*args, **options)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 184, in handle
    return super(Command, self).handle(*items, **options)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/django/core/management/base.py", line 322, in handle
    label_output = self.handle_label(label, **options)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 210, in handle_label
    self.update_backend(label, using)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 239, in update_backend
    end_date=self.end_date)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/haystack/indexes.py", line 157, in build_queryset
    index_qs = self.index_queryset(using=using)
TypeError: index_queryset() got an unexpected keyword argument 'using'

======================================================================
ERROR: test_explore_get_list_only_published (storybase_story.tests.StoryExploreResourceTest)
Test that story exploration endpoint doesn't show unpublished stories
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/PitonFoundation/atlas/apps/storybase_story/tests.py", line 2980, in setUp
    self._rebuild_index()
  File "/home/travis/build/PitonFoundation/atlas/apps/storybase_story/tests.py", line 2985, in _rebuild_index
    call_command('rebuild_index', interactive=False, verbosity=0)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 166, in call_command
    return klass.execute(*args, **defaults)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/django/core/management/base.py", line 220, in execute
    output = self.handle(*args, **options)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/haystack/management/commands/rebuild_index.py", line 15, in handle
    call_command('update_index', **options)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 166, in call_command
    return klass.execute(*args, **defaults)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/django/core/management/base.py", line 220, in execute
    output = self.handle(*args, **options)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 184, in handle
    return super(Command, self).handle(*items, **options)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/django/core/management/base.py", line 322, in handle
    label_output = self.handle_label(label, **options)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 210, in handle_label
    self.update_backend(label, using)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 239, in update_backend
    end_date=self.end_date)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/haystack/indexes.py", line 157, in build_queryset
    index_qs = self.index_queryset(using=using)
TypeError: index_queryset() got an unexpected keyword argument 'using'

----------------------------------------------------------------------
```

**Comment by ghing** [comment]
Fixed by f38e88b. Closing.
