### ISSUE TITLE
Proxy view for Creative Commons license API should handle timeout more gracefully

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#605]
With some frequency, the view that proxies the creative commons API (to get around cross-domain issues) times out.  The client-side code handles the error gracefully, but we should probably catch the timeout error in the view and return a better response back to the client instead of a generic 500 error.  This is the traceback from the timeout:

```
Traceback (most recent call last):

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 47, in view
    return self.dispatch(request, *args, **kwargs)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in dispatch
    return handler(request, *args, **kwargs)

  File "/home/floodlight/webapps/floodlight_production/floodlight/apps/storybase/api/views.py", line 18, in get
    resp = urllib2.urlopen(req)

  File "/usr/local/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)

  File "/usr/local/lib/python2.7/urllib2.py", line 400, in open
    response = self._open(req, data)

  File "/usr/local/lib/python2.7/urllib2.py", line 418, in _open
    '_open', req)

  File "/usr/local/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)

  File "/usr/local/lib/python2.7/urllib2.py", line 1207, in http_open
    return self.do_open(httplib.HTTPConnection, req)

  File "/usr/local/lib/python2.7/urllib2.py", line 1180, in do_open
    r = h.getresponse(buffering=True)

  File "/usr/local/lib/python2.7/httplib.py", line 1030, in getresponse
    response.begin()

  File "/usr/local/lib/python2.7/httplib.py", line 407, in begin
    version, status, reason = self._read_status()

  File "/usr/local/lib/python2.7/httplib.py", line 365, in _read_status
    line = self.fp.readline()

  File "/usr/local/lib/python2.7/socket.py", line 447, in readline
    data = self._sock.recv(self._rbufsize)

timeout: timed out
```

**Comment by ghing** [comment]
The method I used in f640f84 doesn't seem to catch the timeout exception

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
