### ISSUE TITLE
TypeError when unauthenticated user tries to preview a story

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#621]
Traceback:

```
Traceback (most recent call last):

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 47, in view
    return self.dispatch(request, *args, **kwargs)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 28, in _wrapper
    return bound_func(*args, **kwargs)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/menus/utils.py", line 99, in _wrapped
    return func(request, *args, **kwargs)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 24, in bound_func
    return func(self, *args2, **kwargs2)

  File "/home/floodlight/webapps/floodlight_production/floodlight/apps/storybase/views/generic.py", line 21, in dispatch
    return super(ModelIdDetailView, self).dispatch(*args, **kwargs)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in dispatch
    return handler(request, *args, **kwargs)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/views/generic/detail.py", line 99, in get
    context = self.get_context_data(object=self.object)

  File "/home/floodlight/webapps/floodlight_production/floodlight/apps/storybase_story/views.py", line 130, in get_context_data
    context['connected_stories'] = self.object.connected_stories(published_only=False, draft_author=self.request.user)

  File "/home/floodlight/webapps/floodlight_production/floodlight/apps/storybase_story/models.py", line 411, in connected_stories
    qs = qs.filter(Q(status='published') | Q(status='draft', author=draft_author))

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/db/models/query.py", line 550, in filter
    return self._filter_or_exclude(False, *args, **kwargs)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/db/models/query.py", line 568, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1191, in add_q
    self.add_q(child, used_aliases, force_having=force_having)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1191, in add_q
    self.add_q(child, used_aliases, force_having=force_having)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1194, in add_q
    can_reuse=used_aliases, force_having=force_having)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1129, in add_filter
    connector)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/db/models/sql/where.py", line 67, in add
    value = obj.prepare(lookup_type, value)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/db/models/sql/where.py", line 316, in prepare
    return self.field.get_prep_lookup(lookup_type, value)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/db/models/fields/related.py", line 136, in get_prep_lookup
    return self._pk_trace(value, 'get_prep_lookup', lookup_type)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/db/models/fields/related.py", line 209, in _pk_trace
    v = getattr(field, prep_func)(lookup_type, v, **kwargs)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 292, in get_prep_lookup
    return self.get_prep_value(value)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 479, in get_prep_value
    return int(value)

TypeError: int() argument must be a string or a number, not 'AnonymousUser'
```

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
