### ISSUE TITLE
"InvalidFilterError: The 'url' field does not allow filtering." in builder

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#652]
Setting this to low for now because I've only seen one instance of this error.

Traceback:

```
Traceback (most recent call last):

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 48, in view
    return self.dispatch(request, *args, **kwargs)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in _wrapper
    return bound_func(*args, **kwargs)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 21, in bound_func
    return func(self, *args2, **kwargs2)

  File "/home/floodlight/webapps/floodlight_production/floodlight/apps/storybase_story/views.py", line 588, in dispatch
    return super(StoryBuilderView, self).dispatch(*args, **kwargs)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in dispatch
    return handler(request, *args, **kwargs)

  File "/home/floodlight/webapps/floodlight_production/floodlight/apps/storybase_story/views.py", line 581, in get
    context = self.get_context_data(object=self.object, **kwargs)

  File "/home/floodlight/webapps/floodlight_production/floodlight/apps/storybase_story/views.py", line 552, in get_context_data
    context['featured_assets_json'] = mark_safe(self.get_assets_json(featured=True))

  File "/home/floodlight/webapps/floodlight_production/floodlight/apps/storybase_story/views.py", line 348, in get_assets_json
    story_id=story.story_id)

  File "/home/floodlight/webapps/floodlight_production/floodlight/apps/storybase_asset/api.py", line 226, in obj_get_list
    return super(AssetResource, self).obj_get_list(request, **kwargs).filter(q)

  File "/home/floodlight/webapps/floodlight_production/floodlight/apps/storybase/api/resources.py", line 270, in obj_get_list
    obj_list = super(HookedModelResource, self).obj_get_list(request, **kwargs)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/tastypie/resources.py", line 1887, in obj_get_list
    applicable_filters = self.build_filters(filters=filters)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/tastypie/resources.py", line 1789, in build_filters
    lookup_bits = self.check_filtering(field_name, filter_type, filter_bits)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/tastypie/resources.py", line 1685, in check_filtering
    raise InvalidFilterError("The '%s' field does not allow filtering." % field_name)

InvalidFilterError: The 'url' field does not allow filtering.
```

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
