### ISSUE TITLE
Yahoo Geocoder broken

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#700]
Traceback:

```
Traceback (most recent call last):

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/tastypie/resources.py", line 202, in wrapper
    response = callback(request, *args, **kwargs)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/tastypie/resources.py", line 441, in dispatch_list
    return self.dispatch('list', request, **kwargs)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/tastypie/resources.py", line 474, in dispatch
    response = method(request, **kwargs)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/tastypie/resources.py", line 1127, in get_list
    objects = self.obj_get_list(request=request, **self.remove_api_resource_names(kwargs))

  File "/home/floodlight/webapps/floodlight_production/floodlight/apps/storybase_geo/api.py", line 155, in obj_get_list
    for place, (lat, lng) in geocoder.geocode(address, **geocoding_kwargs):

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/geopy/geocoders/yahoo.py", line 39, in geocode
    return self.geocode_url(url, exactly_one)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/geopy/geocoders/yahoo.py", line 42, in geocode_url
    page = urlopen(url)

  File "/usr/local/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)

  File "/usr/local/lib/python2.7/urllib2.py", line 406, in open
    response = meth(req, response)

  File "/usr/local/lib/python2.7/urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)

  File "/usr/local/lib/python2.7/urllib2.py", line 444, in error
    return self._call_chain(*args)

  File "/usr/local/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)

  File "/usr/local/lib/python2.7/urllib2.py", line 527, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

HTTPError: HTTP Error 404: Not Found
```

The Yahoo geopy geocoder uses the URL http://where.yahooapis.com/geocode (see https://github.com/geopy/geopy/blob/master/geopy/geocoders/yahoo.py#L21) which returns a 404 when visited.

**Comment by ghing** [comment]
Apparently the [Yahoo Placefinder API has been shut down](http://tech.groups.yahoo.com/group/ysearchboss/message/5163).  Its replacement is the [Yahoo! BOSS Geo Services](http://developer.yahoo.com/boss/geo/) which is no longer free.  Looks like we'll need to switch geocoders.

**Comment by ghing** [comment]
Added a mock geocoder to make tests less brittle under CI.  Updated STORYBASE_GEOCODER setting in dev, production and staging instances to use the Bing geocoder. Seems to work fine.

**Comment by thedore17** [comment]
So this is still broken?
