### ISSUE TITLE
Error when editing an uploaded image asset in place

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#738]
## To replicate
1. Open a story in the builder.
2. In a container with no asset selected, click the "Image" icon.
   3  Select a file to upload.  And click the "Save Changes" button. After uploading, the image should be shown.
3. Click the "Edit" icon for the image asset you just aded
4. Select a different image from your hard drive and click "Save Changes"
## Expected result

The new image is shown.
## Observed result

An error message is shown.

This is the traceback on the server:

```
Traceback (most recent call last):

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/tastypie/resources.py", line 202, in wrapper
    response = callback(request, *args, **kwargs)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/tastypie/resources.py", line 450, in dispatch_detail
    return self.dispatch('detail', request, **kwargs)

  File "/home/floodlight/webapps/floodlight_production/floodlight/apps/storybase/api/resources.py", line 428, in dispatch
    response = method(request, **kwargs)

  File "/home/floodlight/webapps/floodlight_production/floodlight/apps/storybase/api/resources.py", line 510, in put_detail
    return super(TranslatedModelResource, self).put_detail(request, **kwargs)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/tastypie/resources.py", line 1220, in put_detail
    deserialized = self.deserialize(request, request.raw_post_data, format=request.META.get('CONTENT_TYPE', 'application/json'))

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/http/__init__.py", line 345, in raw_post_data
    return self.body

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/http/__init__.py", line 334, in body
    raise Exception("You cannot access body after reading from request's data stream")

Exception: You cannot access body after reading from request's data stream
```

**Comment by ghing** [comment]
Note that users are still able to change images by removing them and adding a new one.

**Comment by ghing** [comment]
I want to hold off on this until changes for #614 are merged so I don't have to port changes between branches using differing Tastypie APIs.

**Comment by ghing** [comment]
http://stackoverflow.com/a/12576374/386210 has a good breakdown of what's happening here.  I think the solution is to implement `MultipartFileUploadModelResource.put_detail` so that it doesn't try to grab `request.body` if the format is multipart.

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
