### ISSUE TITLE
Code breaks with django-registration 1.0

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#786]
Example traceback:

```
======================================================================
ERROR: test_put_list_non_member (storybase_story.tests.StoryProjectResourceTest)
Test that a user cannot add projects to a story unless they're a member of the project
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/PitonFoundation/atlas/apps/storybase_story/tests.py", line 3878, in test_put_list_non_member
    response = self.api_client.put(uri, format='json', data=put_data)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/tastypie/test.py", line 132, in put
    return self.client.put(uri, **kwargs)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/django/test/client.py", line 477, in put
    response = super(Client, self).put(path, data=data, content_type=content_type, **extra)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/django/test/client.py", line 305, in put
    return self.request(**r)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/django/test/client.py", line 381, in request
    response = self.handler(environ)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/django/test/client.py", line 84, in __call__
    response = self.get_response(request)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 179, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 224, in handle_uncaught_exception
    if resolver.urlconf_module is None:
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 323, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/travis/build/PitonFoundation/atlas/urls.py", line 85, in <module>
    (r'^accounts/', include('storybase_user.registration.backends.extrainfo.urls')),
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 24, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/travis/build/PitonFoundation/atlas/apps/storybase_user/registration/backends/extrainfo/__init__.py", line 10, in <module>
    from registration.backends.default import DefaultBackend
ImportError: cannot import name DefaultBackend
```

**Comment by ghing** [comment]
Adding to "Critical Bugs" milestone as we should support django-registration 1.0 before updating our customizations to close #836.

**Comment by jwirfs-brock** [comment]
On the test "User provides passwords that don't match," the invalid password message appears above each password field. It only needs to show up once, above the first password field.

Screen shot:
![screen shot 2013-08-16 at 11 52 08 am](https://f.cloud.github.com/assets/1020518/976385/f7adaaa2-068b-11e3-9f4c-86b758e1013a.png)

**Comment by jwirfs-brock** [comment]
For the test, "User provides passwords that don't match" the error message appears above the email address field. This is inconsistent with the password length message, which appeared above the password field.

I suggest displaying this message above the password field, too.

Screenshot of what it looks like now:
![screen shot 2013-08-16 at 12 01 28 pm](https://f.cloud.github.com/assets/1020518/976467/4bfe8328-068d-11e3-83c3-ed8317596722.png)
