### ISSUE TITLE
render_thumbnail() should handle InvalidImageFormatError more gracefully

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#863]
I originally noticed this when a user uploaded an EPS file for the featured image of an organization.  We should catch `InvalidImageFormatError`, log the error and just cause the default image to be shown.

Example traceback:

```
Traceback (most recent call last):

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 136, in get_response
    response = response.render()

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/response.py", line 104, in render
    self._set_content(self.rendered_content)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/response.py", line 81, in rendered_content
    content = template.render(context)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/base.py", line 823, in render
    bit = self.render_node(node, context)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/base.py", line 837, in render_node
    return node.render(context)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/base.py", line 823, in render
    bit = self.render_node(node, context)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/base.py", line 837, in render_node
    return node.render(context)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/base.py", line 823, in render
    bit = self.render_node(node, context)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/base.py", line 837, in render_node
    return node.render(context)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/base.py", line 823, in render
    bit = self.render_node(node, context)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/base.py", line 837, in render_node
    return node.render(context)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/classytags/core.py", line 102, in render
    return self.render_tag(context, **kwargs)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/sekizai/templatetags/sekizai_tags.py", line 75, in render_tag
    rendered_contents = nodelist.render(context)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/base.py", line 823, in render
    bit = self.render_node(node, context)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/base.py", line 837, in render_node
    return node.render(context)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/base.py", line 823, in render
    bit = self.render_node(node, context)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/base.py", line 837, in render_node
    return node.render(context)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/base.py", line 823, in render
    bit = self.render_node(node, context)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/base.py", line 837, in render_node
    return node.render(context)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/base.py", line 823, in render
    bit = self.render_node(node, context)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/base.py", line 837, in render_node
    return node.render(context)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/template/base.py", line 1107, in render
    return func(*resolved_args, **resolved_kwargs)

  File "/home/floodlight/webapps/floodlight_production/floodlight/apps/storybase/templatetags/storybase_tags.py", line 74, in featured_asset
    return obj.render_featured_asset(format='html', width=width)

  File "/home/floodlight/webapps/floodlight_production/floodlight/apps/storybase_asset/models.py", line 695, in render_featured_asset
    **thumbnail_options)

  File "/home/floodlight/webapps/floodlight_production/floodlight/apps/storybase_asset/models.py", line 91, in render_thumbnail
    width, height, **kwargs)

  File "/home/floodlight/webapps/floodlight_production/floodlight/apps/storybase_asset/models.py", line 108, in render_thumbnail_html
    url = self.get_thumbnail_url(width, height)

  File "/home/floodlight/webapps/floodlight_production/floodlight/apps/storybase_asset/models.py", line 591, in get_thumbnail_url
    thumbnail = self.get_thumbnail(thumbnail_options)

  File "/home/floodlight/webapps/floodlight_production/floodlight/apps/storybase_asset/models.py", line 575, in get_thumbnail
    return thumbnailer.get_thumbnail(thumbnail_options)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/easy_thumbnails/files.py", line 396, in get_thumbnail
    thumbnail = self.generate_thumbnail(thumbnail_options)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/easy_thumbnails/files.py", line 292, in generate_thumbnail
    "The source file does not appear to be an image")

InvalidImageFormatError: The source file does not appear to be an image
```

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
