### ISSUE TITLE
Error when creating dataset with URL longer than 200 characters 

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#940]
Traceback:

```
Traceback (most recent call last):

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/tastypie/resources.py", line 195, in wrapper
    response = callback(request, *args, **kwargs)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/tastypie/resources.py", line 426, in dispatch_list
    return self.dispatch('list', request, **kwargs)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/tastypie/resources.py", line 458, in dispatch
    response = method(request, **kwargs)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/tastypie/resources.py", line 1320, in post_list
    updated_bundle = self.obj_create(bundle, **self.remove_api_resource_names(kwargs))

  File "/home/floodlight/webapps/floodlight_production/floodlight/apps/storybase_asset/api.py", line 420, in obj_create
    bundle, **kwargs)

  File "/home/floodlight/webapps/floodlight_production/floodlight/apps/storybase/api/resources.py", line 325, in obj_create
    return self.save(bundle)

  File "/home/floodlight/webapps/floodlight_production/floodlight/apps/storybase/api/resources.py", line 301, in save
    bundle.obj.save()

  File "/home/floodlight/webapps/floodlight_production/floodlight/apps/storybase_asset/models.py", line 873, in save
    super(ExternalDataSet, self).save(*args, **kwargs)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/db/models/base.py", line 546, in save
    force_update=force_update, update_fields=update_fields)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/db/models/base.py", line 650, in save_base
    result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/db/models/manager.py", line 215, in _insert
    return insert_query(self.model, objs, fields, **kwargs)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/db/models/query.py", line 1675, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 943, in execute_sql
    cursor.execute(sql, params)

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 58, in execute
    six.reraise(utils.DatabaseError, utils.DatabaseError(*tuple(e.args)), sys.exc_info()[2])

  File "/home/floodlight/webapps/floodlight_production/venv/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 54, in execute
    return self.cursor.execute(query, args)

DatabaseError: value too long for type character varying(200)
```

**Comment by ghing** [comment]
URL fields are implemented as varchar(200) at the database level in Postgres (but apparently they don't have a limit in SQLite!).  There's no equivalent to a `max_length` option for Tastypie fields.  I bet we can just add a check in `DataSetValidation.is_valid()`
